# Generated by Django 5.2.9 on 2025-12-07 15:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='RecipientDetails',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'recipient_name',
                    models.CharField(max_length=150, verbose_name='Наименование получателя'),
                ),
                (
                    'recipient_inn',
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='ИНН должен состоять либо из 10, либо из 12 цифр',
                                regex='^(\\d{10}|\\d{12})$',
                            )
                        ],
                        verbose_name='ИНН получателя',
                    ),
                ),
                (
                    'recipient_kpp',
                    models.CharField(
                        blank=True,
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Значение должно содержать ровно 9 цифр',
                                regex='^\\d{9}$',
                            )
                        ],
                        verbose_name='КПП получателя',
                    ),
                ),
                (
                    'bank_name',
                    models.CharField(max_length=150, verbose_name='Наименование банка получателя'),
                ),
                (
                    'bank_bik',
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Значение должно содержать ровно 9 цифр',
                                regex='^\\d{9}$',
                            )
                        ],
                        verbose_name='БИК',
                    ),
                ),
                (
                    'correspondent_account',
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Значение должно содержать ровно 20 цифр',
                                regex='^\\d{20}$',
                            )
                        ],
                        verbose_name='Кор. счет',
                    ),
                ),
                (
                    'account_number',
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Значение должно содержать ровно 20 цифр',
                                regex='^\\d{20}$',
                            )
                        ],
                        verbose_name='Номер счета',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Реквизиты получателя',
                'verbose_name_plural': 'Реквизиты получателей',
            },
        ),
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_archived',
                    models.BooleanField(default=False, verbose_name='Архивная'),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name='Сумма выплаты',
                    ),
                ),
                (
                    'currency',
                    models.CharField(
                        choices=[
                            ('RUB', 'Российский рубль'),
                            ('USD', 'Доллар США'),
                            ('EUR', 'Евро'),
                            ('CNY', 'Китайский юань'),
                        ],
                        verbose_name='Валюта',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('NEW', 'Новая'),
                            ('APPROVED', 'Одобрена'),
                            ('REJECTED', 'Отклонена'),
                            ('PAID', 'Выплачена'),
                        ],
                        default='NEW',
                        verbose_name='Статус',
                    ),
                ),
                (
                    'comment',
                    models.CharField(blank=True, max_length=256, verbose_name='Комментарий'),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Время редактирования'),
                ),
                (
                    'recipient_details',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payment_applications',
                        to='payment_applications.recipientdetails',
                        verbose_name='Реквизиты получателя',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заявка на выплату',
                'verbose_name_plural': 'Заявки на выплату',
            },
        ),
    ]
